spring:
  datasource:
    username: root
    password: wzz123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://8.129.237.25:3306/shop?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: "com.azen.root.bean"
  mapper-locations:
    - classpath*:mappers/*.xml
  configuration:
    use-actual-param-name: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  arams: count=countSql
server:
  port: 8080
  servlet:
    session:
      cookie:
        name: sessionid_1